### ISSUE TITLE
shortcuts for keyboard

### ISSUE THREAD

**Issue by mohammedmatar** [danields761/status-bar-breadcrumb#5]
hi @danields761 !
thank you for your great tool,
i hope if there is an ability to configure some shortcuts to focus on the breadcrumb.

**Comment by danields761** [comment]
Hello, @mohammedmatar 
Thanks You for nice review!

Can You elaborate: what exactly You mean telling "shortcuts to focus on the breadcrumb"? What kind of focus action? 
There are no actions happen when mouse hover SB item, but clicking on some of it will initiate navigation menu. 
Did you mean some key which activate this menu? Plus something like left and right arrow which helps navigate throught files hierarchy in up and down directions?

**Comment by bladnman** [comment]
I can second this idea. It's exactly why I came to the repo, looking for info about it. 

In other editors I have been able to set up a keystroke to get a selection onto the breadcrumb list. Then moving left or right I could select a folder and hit enter. This would open a panel with the files in that directory... much like your `NavigationQuickPickMenu`. In fact, maybe if you at least offer a shortcut key to open your pick menu with the "last folder" in the list that would suffice!

**Comment by danields761** [comment]
Hi, @bladnman 

> In fact, maybe if you at least offer a shortcut key to open your pick menu with the "last folder" in the list that would suffice!

Yeah, sounds useful, i will implement it soon

**Comment by bladnman** [comment]
Sweet!

I've added a key binding for these but I'm getting errors:

Running the contributed command:'statusBarBreadcrumb.showSameLevelFilesForGiven' failed.

**Comment by danields761** [comment]
Hi,

@bladnman, thanks for bug report, i had released new version which fixes this error :)
Also, if you would like to fill bug report within closed issue, please, open the new one :)
